global using HarmonyLib;
global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Net.Http;
global using System.Threading;
global using System.Threading.Tasks;
global using ASP.Roles.Core;
global using static ASP.Translator;